-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity leading_ones_templat is
port (
    ap_ready : OUT STD_LOGIC;
    din_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (4 downto 0) );
end;


architecture behav of leading_ones_templat is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal call_ret_leading_ones_32_s_fu_12_ap_ready : STD_LOGIC;
    signal call_ret_leading_ones_32_s_fu_12_ap_return_0 : STD_LOGIC_VECTOR (0 downto 0);
    signal call_ret_leading_ones_32_s_fu_12_ap_return_1 : STD_LOGIC_VECTOR (4 downto 0);

    component leading_ones_32_s IS
    port (
        ap_ready : OUT STD_LOGIC;
        din_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (4 downto 0) );
    end component;



begin
    call_ret_leading_ones_32_s_fu_12 : component leading_ones_32_s
    port map (
        ap_ready => call_ret_leading_ones_32_s_fu_12_ap_ready,
        din_V_read => din_V_read,
        ap_return_0 => call_ret_leading_ones_32_s_fu_12_ap_return_0,
        ap_return_1 => call_ret_leading_ones_32_s_fu_12_ap_return_1);




    ap_ready <= ap_const_logic_1;
    ap_return_0 <= call_ret_leading_ones_32_s_fu_12_ap_return_0;
    ap_return_1 <= call_ret_leading_ones_32_s_fu_12_ap_return_1;
end behav;
