#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("leadone_in_V", 32, hls_in, 0, "ap_none", "in_data", 1),
	Port_Property("leadone_out_V", 5, hls_out, 1, "ap_vld", "out_data", 1),
	Port_Property("leadone_out_V_ap_vld", 1, hls_out, 1, "ap_vld", "out_vld", 1),
	Port_Property("leadone_ret", 1, hls_out, 2, "ap_vld", "out_data", 1),
	Port_Property("leadone_ret_ap_vld", 1, hls_out, 2, "ap_vld", "out_vld", 1),
	Port_Property("mux_in_0_V", 8, hls_in, 3, "ap_none", "in_data", 1),
	Port_Property("mux_in_1_V", 8, hls_in, 4, "ap_none", "in_data", 1),
	Port_Property("mux_in_2_V", 8, hls_in, 5, "ap_none", "in_data", 1),
	Port_Property("mux_in_3_V", 8, hls_in, 6, "ap_none", "in_data", 1),
	Port_Property("mux_in_4_V", 8, hls_in, 7, "ap_none", "in_data", 1),
	Port_Property("mux_in_5_V", 8, hls_in, 8, "ap_none", "in_data", 1),
	Port_Property("mux_in_6_V", 8, hls_in, 9, "ap_none", "in_data", 1),
	Port_Property("mux_in_7_V", 8, hls_in, 10, "ap_none", "in_data", 1),
	Port_Property("mux_sel_onehot_V", 8, hls_in, 11, "ap_none", "in_data", 1),
	Port_Property("mux_sel0_V", 3, hls_in, 12, "ap_none", "in_data", 1),
	Port_Property("mux_sel1_V", 3, hls_in, 13, "ap_none", "in_data", 1),
	Port_Property("mux_s", 1, hls_in, 14, "ap_none", "in_data", 1),
	Port_Property("mux_ret_V", 8, hls_out, 15, "ap_vld", "out_data", 1),
	Port_Property("mux_ret_V_ap_vld", 1, hls_out, 15, "ap_vld", "out_vld", 1),
	Port_Property("max_in_0", 32, hls_in, 16, "ap_none", "in_data", 1),
	Port_Property("max_in_1", 32, hls_in, 17, "ap_none", "in_data", 1),
	Port_Property("max_in_2", 32, hls_in, 18, "ap_none", "in_data", 1),
	Port_Property("max_in_3", 32, hls_in, 19, "ap_none", "in_data", 1),
	Port_Property("max_in_4", 32, hls_in, 20, "ap_none", "in_data", 1),
	Port_Property("max_in_5", 32, hls_in, 21, "ap_none", "in_data", 1),
	Port_Property("max_in_6", 32, hls_in, 22, "ap_none", "in_data", 1),
	Port_Property("max_in_7", 32, hls_in, 23, "ap_none", "in_data", 1),
	Port_Property("max_out", 32, hls_out, 24, "ap_vld", "out_data", 1),
	Port_Property("max_out_ap_vld", 1, hls_out, 24, "ap_vld", "out_vld", 1),
	Port_Property("mode", 32, hls_in, 25, "ap_none", "in_data", 1),
};
const char* HLS_Design_Meta::dut_name = "top";
