-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity mux_2to1 is
port (
    ap_ready : OUT STD_LOGIC;
    din_0_V_read : IN STD_LOGIC_VECTOR (7 downto 0);
    din_1_V_read : IN STD_LOGIC_VECTOR (7 downto 0);
    sel : IN STD_LOGIC;
    ap_return : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of mux_2to1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal select_ln6_fu_28_p0 : STD_LOGIC_VECTOR (0 downto 0);


begin



    ap_ready <= ap_const_logic_1;
    ap_return <= 
        din_1_V_read when (select_ln6_fu_28_p0(0) = '1') else 
        din_0_V_read;
    select_ln6_fu_28_p0 <= (0=>sel, others=>'-');
end behav;
